#!/bin/bash

datafilepath="datafile$$"
if [ $# = 1 ]; then
	cat > "$datafilepath"
elif [ $# = 2 ]; then
	datafilepath=$2
fi

# echos number of rows followed by a space and number of columns
dims(){
	numberRows=0;
	numberColumns=0;
	while read myLine
	do
		# will increment numberRows by 1 each time a new line is detected
		numberRows=`expr $numberRows + 1`
		
		# will count total number of elements and then divide by number of rows to get number of columns
		for i in $myLine
		do
			numberColumns=`expr $numberColumns + 1`
		done	
		
	
	done < $1
	
	#divides numberColumns(currently total count of all numbers) by numberRows to get numberColumns
	numberColumns=`expr $numberColumns / $numberRows`
	echo "$numberRows $numberColumns"
}

transpose(){
	echo "transpose called with $1"
}

# if first argument is dims
if [ $1 = "dims" ]; then
	
	# if too many arguments were inserted
	if [ $# -gt 2 ]; then
		echo "Too many arguments" 1>&2
		exit 1
	fi
	
	# if second argument was an invalid file
	if [[ ! -f "$datafilepath" ]]; then
		echo "Not a valid file" 1>&2
		exit 1
	fi
	
	# if file cannot be read
	if [[ ! -r "$datafilepath" ]]; then
		echo "File could not be read" 1>&2
		exit 1
	fi
	
	# will call dims if amount of arguements was correct and second argument was a valid file
	dims $datafilepath
fi


