#!/bin/bash


numberRows=0
numberColumns=0
newLine=""
newMatrix=""
lineNum=1

# echos number of rows followed by a space and number of columns
dims(){

	while read myLine
	do
		# will increment numberRows by 1 each time a new line is detected
		numberRows=`expr $numberRows + 1`
		
		# will count total number of elements and then divide by number of rows to get number of columns
		for i in $myLine
		do
			numberColumns=`expr $numberColumns + 1`
		done	
		
	
	done < $1
	
	#divides numberColumns(currently total count of all numbers) by numberRows to get numberColumns
	numberColumns=`expr $numberColumns / $numberRows`
}

# transposes a matrix
transpose(){
	# cut starts from 1, so have to offset
	column=1
	
	#loops through each column
	while [ $column -lt `expr $numberColumns + 1` ]
	do
		
		#cuts each column into newLine then replaces all \n with \t to make one row
		newLine=`cut -f $column $datafilepath`
		newLine=$(echo "$newLine" | tr '\n' '\t')
		
		# removing the trailing \the
		newLine=${newLine%?}
		
		# starts a new line if it is not the first line
		if [ $column -ne 1 ]; then
			newMatrix+="\n"
		fi
		
		#adds newLine to newMatrix and then increases column
		newMatrix+="$newLine"
		column=`expr $column + 1`
	done
}

# determines the mean of each column of column of a matrix
# calculates the mean by taking the transpose of the matrix and sums across the rows then
# divides by how many items there are
mean(){

	columnAverages=""
	while read fileLine
	do
		sum=0
		count=0	
		average=0
		
		# sums up each line and increases count by one on every number
		for i in $fileLine
		do
			num=$i
			sum=`expr $sum + $num`
			count=`expr $count + 1`
		done
		
		#calculates average
		average=$(( ($sum + ($count/2)*( ($sum>0)*2-1 )) / $count ))
		
		# will insert tab before the average unless it is the average of the first column
		if [ $lineNum -ne 1 ]; then
			columnAverages+="\t"
		fi
		
		
		# concatenates newly calculated average with other column averages and increments lineNum
		columnAverages+=$average
		lineNum=`expr $lineNum + 1`
		
	done < $1
	echo -e "$columnAverages"
}

add(){
	while read -u 3 left && read -u 4 right
	do
		sum=0
		for i in $left $right
		do
			sum=`expr $sum + $i`
			echo "$sum"
		done

	done 3< $1 4< $2

}

# if first argument is dims or transpose or mean
if [ $1 = "dims" ] || [ $1 = "transpose" ] || [ $1 = "mean" ]; then
	
	datafilepath="datafile$$"
	if [ $# = 1 ]; then
		cat > "$datafilepath"
	elif [ $# = 2 ]; then
		datafilepath=$2
	fi
	
	# if too many arguments were inserted
	if [ $# -gt 2 ]; then
		echo "Too many arguments" 1>&2
		exit 1
	fi
	
	# if second argument was an invalid file
	if [[ ! -f "$datafilepath" ]]; then
		echo "Not a valid file" 1>&2
		exit 1
	fi
	
	# if file cannot be read
	if [[ ! -r "$datafilepath" ]]; then
		echo "File could not be read" 1>&2
		exit 1
	fi
	
	# will call dims if amount of arguments was correct and second argument was a valid file
	dims $datafilepath
	
	# if first argument is dims, then will echo dimensions out
	if [ $1 = "dims" ]; then
		echo "$numberRows $numberColumns"
		exit 0
	fi

	
	# will transpose matrix and echo out if first argument was transpose
	transpose $datafilepath
	if [ $1 = "transpose" ]; then
		echo -e "$newMatrix"
		exit 0
	fi
	
	# puts transposed matrix in a new file to use for mean and then removes it
	echo -e "$newMatrix" > tempMatrix89574
	mean tempMatrix89574
	rm tempMatrix89574


# if first argument is add
elif [ $1 = "add" ]; then

	m1dimensions=""
	m2dimensions=""
	
	# if the wrong number of arguments were inserted
	if [ $# -ne 3 ]; then
		echo "Wrong number of arguments" 1>&2
		exit 1
	fi
	
	# if either file cannot be read
	if [[ ! -r "$2" ]] || [[ ! -r "$3" ]]; then
		echo "File could not be read" 1>&2
		exit 1
	fi
	
	# gets dimensions of both files to compare them
	dims $2
	m1dimensions+="$numberRows $numberColumns"
	numberRows=0
	numberColumns=0
	dims $3
	m2dimensions+="$numberRows $numberColumns"
	
	if [ "$m1dimensions" != "$m2dimensions" ]; then
		echo "File dimensions did not match" 1>&2
		exit 1
	fi
	
	add $2 $3

fi




