#!/bin/bash

totalLines=0 

#defining function before calling
lineCount(){ 
    for file in ./* ; do 
		# if file is a directory, will change to that directory
		# and call allLines on that directory, then go back to parent directory
        if [[ -d "$file" ]]; then 
			cd "$file"
			lineCount
			cd ..
			
		
		# if file is a file
        elif [[ -f "$file" ]]; then 
			
			#will not count lines in this file
			if [ "$file" == "./allLines" ]; then
				echo "$file will not be counted"
			else
				echo "$file"
			fi
        fi
    done
}

lineCount
echo "$totalLines" 