#!/bin/bash

totalLines=0 
linesInFile=0

#defining function before calling
lineCount(){ 
    for file in ./* ; do 
		# if file is a directory, will change to that directory
		# and call allLines on that directory, then go back to parent directory
        if [[ -d "$file" ]]; then 
			cd "$file"
			lineCount
			cd ..
			
		
		# if file is a file
        elif [[ -f "$file" ]]; then 
			((linesInFile = $(wc -l "$file" | cut -f1 -d " ")))
			
			#will not count lines in this script
			if [ "$file" == "./allLines" ]; then
				echo "The $linesInFile lines in this script will not be counted."
			
			#will add number of lines in file to totalLines
			else
				totalLines=`expr $linesInFile + $totalLines`
			fi
        fi
    done
}

lineCount
echo "$totalLines lines are in this directory." 